### ISSUE TITLE
where to imply image "preserve" or "prune"

### ISSUE THREAD

**Issue by c7785812** [huofushuo/SID#10]
![image](https://github.com/user-attachments/assets/d30e908e-86b5-455f-9a0f-41c50f318f6f)
In pope_eval.py, image_cd is set to the same as image, I wonder where to imply image "preserve" or "prune"? 

Thank you!

**Comment by huofushuo** [comment]
Hello! the implementations are mainly in modeling_llama.py --def forward ( ). Thanks!
