### ISSUE TITLE
LLaVA-Next Details

### ISSUE THREAD

**Issue by stevenyoung18** [huofushuo/SID#12]
May you please give the version and LLM that LLAVA-NEXT used? Is it llava-llama-8b，llava-v1.6-vicuna-7b or other version? Thanks

**Comment by huofushuo** [comment]
Thanks for the attention! LLAVA-NEXT uses the llava-llama-8b. More details please refer to https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/docs/LLaVA-NeXT.md and pay attention to transformers versions. Thanks!

**Comment by stevenyoung18** [comment]
I used the LLava-LLaMA3-8B model to reproduce the CHAIR metrics from your LLava-Next paper. However, the results from the greedy method were CHAIRS: 28.0 and CHAIRi: 7.4, which are not close to the values reported in Table 4 of your paper. In my experiments, the average length of the generated captions was 150, while the generation parameters were kept the same as those in LLava-1.5. Could you please share the average length of the generated captions in your experiments? Thank you!

**Comment by huofushuo** [comment]
Thanks for the attention! Please note that the length of the generated captions is 512 not 150. We randomly choose 500 images from MSCOCO to run all experiments, which greatly affects the results.  Thanks.

**Comment by huofushuo** [comment]
The selected 500 images are chosen randomly based on the random seed, which matters for the numerical results. Thanks!
