### ISSUE TITLE
您好，SID是一个非常好的工作。请问，SID具体是在哪个.py文件以及哪个函数中实施。再次感谢

### ISSUE THREAD

**Issue by qppwdd0324** [huofushuo/SID#3]

**Comment by huofushuo** [comment]
Thanks for your attention. You mainly need to modify the modeling strategy like modeling_llama.py--def forward() and corresponding decoding strategy like vcd_sample.py --def sample(). The corresponding intermediate variables also need to be passed.

**Comment by qppwdd0324** [comment]
<img width="784" alt="屏幕截图 2024-08-15 104001" src="https://github.com/user-attachments/assets/40830784-3e20-47fd-9461-e61bf8aebed7">
您好，我在运行您的代码时，不管哪个代码都遇到了相似的问题，您有什么好的建议么

**Comment by huofushuo** [comment]
We just test in the ubuntu 22.04. It seems that you do not install `transformers' well.
