### ISSUE TITLE
Questions about codes

### ISSUE THREAD

**Issue by Ivesfu** [huofushuo/SID#4]
Thank you for your excellent work! I have a few questions after reviewing the code.

I understand that vcd_sample should support three modes: use_vcd, use_cd, and use_icd, but it seems that only the latter two are implemented. Additionally, at [this line](https://github.com/huofushuo/SID/blob/5a614abc775a58411589e932d83bebbc3f9cc058/vcd_sample.py#L181), the implementation appears to differ from the paper. Specifically, cd_alpha and cd_beta don’t seem to be utilized.

Could you please advise on how to modify the code to match the paper’s implementation? Have you considered updating the code to reflect the settings used in the paper?

Thank you.

**Comment by huofushuo** [comment]
Thanks for your attention. Both use_vcd and use_cd have the same decoding strategy (i.e., use_cd) in the vcd_sample.py. cd_alpha is set to 1 (diffs = (1+cd_alpha)*next_token_logits - cd_alpha*next_token_logits_cd) and Adaptive Plausibility Constraints (v2) is the same as VCD. We add codes comments.

**Comment by xqxscut** [comment]
> Thanks for your attention. Both use_vcd and use_cd have the same decoding strategy (i.e., use_cd) in the vcd_sample.py. cd_alpha is set to 1 (diffs = (1+cd_alpha)_next_token_logits - cd_alpha_next_token_logits_cd) and Adaptive Plausibility Constraints (v2) is the same as VCD. We add codes comments.

Dear authors, does this mean that the only difference between SID and VCD is that VCD incorporates global noise perturbation (i.e., image_cd = add_diffusion_noise(image, args.noise_step))? In other words, is VCD in the code essentially just a globally noised version of SID?
