### ISSUE TITLE
您好，我在运行pope_eval.py时遇到了错误

### ISSUE THREAD

**Issue by qppwdd0324** [huofushuo/SID#6]
您好，我在运行pope_eval.py时遇到了错误。我很确定，我的运行环境没有问题。
<img width="789" alt="屏幕截图 2024-09-02 135958" src="https://github.com/user-attachments/assets/c7da8959-17f0-4a24-a65a-a70c29c01570">
<img width="794" alt="屏幕截图 2024-09-02 140011" src="https://github.com/user-attachments/assets/f9527caa-df1e-4d10-b02a-198fa5565c3e">
<img width="860" alt="屏幕截图 2024-09-02 135945" src="https://github.com/user-attachments/assets/ed8772ce-ad27-417d-8c2e-332d4878a805">

**Comment by qppwdd0324** [comment]
以下是我的超参数
model='instructblip', pope_type='coco_adversarial', gpu_id=0, data_path='D:\\learn\\python_file\\HALC\\HALC\\eval_dataset/val2014/val2014/', batch_size=1, num_workers=1, answers_file='', noise_step=500, use_cd=True, use_icd=False, use_vcd=False, sample_greedy=True, use_fast_v=True, fast_v_inplace=False, fast_v_attention_rank=100, fast_v_attention_rank_add=100, fast_v_agg_layer=2, fast_v_sys_length=None, fast_v_image_token_length=None, beam=1, sample=True, scale_factor=50, threshold=15, num_attn_candidates=5, penalty_weights=1.0, opera=False, cd_alpha=1, cd_beta=0.1, options=None

**Comment by huofushuo** [comment]
Please adjust --fast-v-attention-rank, because the number of Instructblip has 32 output tokens.

**Comment by qppwdd0324** [comment]
> 请调整 --fast-v-attention-rank，因为 Instructblip 的数量有 32 个输出标记。

thanks

**Comment by darwann** [comment]
> Please adjust --fast-v-attention-rank, because the number of Instructblip has 32 output tokens.

Hi, in the implementation details of the InstructBlip model in the experiments, what value is set for the hyperparameter --fast-v-attention-rank?
