### ISSUE TITLE
About the visualization in paper

### ISSUE THREAD

**Issue by tbbbk** [huofushuo/SID#7]
![image](https://github.com/user-attachments/assets/6c92d392-faaf-462a-bad4-2f66fcf462ac)
Hello! Thank u guys for such a amazing work. However, I am still confused about some details about the experiments:

Could you tell me how did you visualize these pictures.

**Comment by huofushuo** [comment]
Thanks for the attention! We first calculate the QK attention scores and record the indexes, then crop the image based on the indexes, finally merge the cropped images with original image (adjust transparency) in the 'Visio'.
